SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE CLIENTES];

SELECT [NOME],[ESTADO] 
       FROM [TABELA DE CLIENTES]
	   ORDER BY [NOME]
;

SELECT [ESTADO],[NOME] FROM [TABELA DE CLIENTES];

