USE SUCOS_VENDAS

---SELECT SIMPLES
SELECT [NOME]
     , [CPF]
	 , [ESTADO]
FROM [TABELA DE CLIENTES];

---SELECT COM APELIDOS NO TEMAS DA TABELA
USE SUCOS_VENDAS
SELECT [NOME] AS [NOME DO CLIENTE]
     , [CPF]
	 , [ESTADO] AS [UF]
FROM [TABELA DE CLIENTES];


USE SUCOS_VENDAS
SELECT 
     [MATRICULA] AS IDENTIFICADOR
	,[NOME] AS [NOME DO VENDEDOR]
FROM [TABELA DE VENDEDORES];


USE SUCOS_VENDAS
SELECT [SABOR] FROM [TABELA DE PRODUTOS];


USE SUCOS_VENDAS
SELECT DISTINCT [SABOR] FROM [TABELA DE PRODUTOS];


USE SUCOS_VENDAS

SELECT [NOME] AS [NOME DO CLIENTE], [ESTADO] AS [UF], [PRIMEIRA COMPRA]
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;

-- SUCOS COM O VALOR DE R$ 7.00 
SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] = 7.00;

-- SUCOS COM O VALOR MAIOR QUE R$ 7.00 
SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] > 7.00
ORDER BY [PRECO DE LISTA];

-- SUCOS COM O VALOR MENOR OU IGUAL A R$ 7.00 
SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] <= 7.00
ORDER BY [PRECO DE LISTA];

-- DATA DE NASCIMENTO ACIMA DO ANO DE 1995
SELECT [NOME],[DATA DE NASCIMENTO]
FROM [TABELA DE CLIENTES]
WHERE YEAR([DATA DE NASCIMENTO]) > '1995';


SELECT [NOME]
      ,[BAIRRO]
FROM [TABELA DE CLIENTES]
WHERE [BAIRRO] = 'Copacabana' OR [BAIRRO] = 'Tijuca'
;


SELECT [NOME]
      ,[ESTADO]
	  ,[PRIMEIRA COMPRA]
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1 AND [ESTADO] = 'SP'
;

SELECT * FROM [TABELA DE VENDEDORES] 
WHERE [PERCENTUAL COMISSAO] <= 0.08;

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [PRECO DE LISTA] <= 6 AND EMBALAGEM = 'LATA';

SELECT * FROM [TABELA DE CLIENTES] 
WHERE NOT ([ESTADO] = 'SP' OR [ESTADO] = 'RJ');

